name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Version Tag（e.g. : v1.0.0）
    branches:
      - 'develop'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$TAG_NAME" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$TAG_NAME" \
            --generate-notes

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./path/to/your/asset.zip
            asset_name: asset.zip
            asset_content_type: application/zip
